config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :reviews
  resources :genres
  resources :authors
  resources :books
  resources :categories
  resources :items
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
   root'books#index'

   get 'about', to: 'about#index'
   get '/categories', to: 'categories#show', as: 'custom_categories_path'
  # root "articles#index"
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :books

  validates :name, presence: true
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :set_genre, only: %i[ show edit update destroy ]

  # GET /genres or /genres.json
  def index
    @genres = Genre.all
  end

  # GET /genres/1 or /genres/1.json
  def show
  end

  # GET /genres/new
  def new
    @genre = Genre.new
  end

  # GET /genres/1/edit
  def edit
  end

  # POST /genres or /genres.json
  def create
    @genre = Genre.new(genre_params)

    respond_to do |format|
      if @genre.save
        format.html { redirect_to genre_url(@genre), notice: "Genre was successfully created." }
        format.json { render :show, status: :created, location: @genre }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genres/1 or /genres/1.json
  def update
    respond_to do |format|
      if @genre.update(genre_params)
        format.html { redirect_to genre_url(@genre), notice: "Genre was successfully updated." }
        format.json { render :show, status: :ok, location: @genre }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genres/1 or /genres/1.json
  def destroy
    @genre.destroy

    respond_to do |format|
      format.html { redirect_to genres_url, notice: "Genre was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genre
      @genre = Genre.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def genre_params
      params.require(:genre).permit(:name)
    end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/_form.html.erb
<%= form_with(model: genre) do |form| %>
  <% if genre.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(genre.errors.count, "error") %> prohibited this genre from being saved:</h2>

      <ul>
        <% genre.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/genres/_genre.html.erb
<div id="<%= dom_id genre %>">
  <p>
    <strong>Name:</strong>
    <%= genre.name %>
  </p>

</div>

app/views/genres/edit.html.erb
<h1>Editing genre</h1>

<%= render "form", genre: @genre %>

<br>

<div>
  <%= link_to "Show this genre", @genre %> |
  <%= link_to "Back to genres", genres_path %>
</div>

app/views/genres/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Genres</h1>

<div id="genres">
  <% @genres.each do |genre| %>
    <%= render genre %>
    <p>
      <%= link_to "Show this genre", genre %>
    </p>
  <% end %>
</div>

<%= link_to "New genre", new_genre_path %>

app/views/genres/new.html.erb
<h1>New genre</h1>

<%= render "form", genre: @genre %>

<br>

<div>
  <%= link_to "Back to genres", genres_path %>
</div>

app/views/genres/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @genre %>

<div>
  <%= link_to "Edit this genre", edit_genre_path(@genre) %> |
  <%= link_to "Back to genres", genres_path %>

  <%= button_to "Destroy this genre", @genre, method: :delete %>
</div>