config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :reviews
  resources :genres
  resources :authors
  resources :books
  resources :categories
  resources :items
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
   root'books#index'

   get 'about', to: 'about#index'
   get '/categories', to: 'categories#show', as: 'custom_categories_path'
  # root "articles#index"
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  belongs_to :genre


  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.all
end

def index
  @items = Item.all
end

def index
  @books = Book.page(params[:page]).per(10)
end



  # GET /books/1 or /books/1.json
  def show
    @book = Book.find(params[:id])
  end



  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :description, :author_id, :genre_id, :price)
    end
  end

  def index
    @books = if params[:search]
               Book.where('title LIKE ?', "%#{params[:search]}%")
             else
               Book.all
             end
  end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<div id="<%= dom_id book %>">
  <p>
    <strong>Title:</strong>
    <%= book.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= book.description %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= book.author_id %>
  </p>

  <p>
    <strong>Genre:</strong>
    <%= book.genre_id %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= book.price %>
  </p>

</div>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>
      <ul>
        <% book.errors.full_messages.each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :author_id, style: "display: block" %>
    <%= form.text_field :author_id %>
  </div>

  <div>
    <%= form.label :genre_id, style: "display: block" %>
    <%= form.text_field :genre_id %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Show this book", @book %> |
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Books</h1>

<div id="books">
  <% @books.each do |book| %>

    <%= render book %>
    <p>
      <%= link_to "Show this book", book %>
    </p>
  <% end %>
</div>

<%= link_to "New book", new_book_path %>
<table>
  <thead>
<tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.description %></td>
        <td><%= book.author.name %></td>
        <td><%= book.genre.name %></td>
        <td><%= book.price %></td>
      </tr>
    <% end %>
  </tbody>


  </thead>
  <tbody>
    <% @books.each do |book| %>

  </tbody>
</table>

<%= paginate @books %>
<% end %>


<%= form_tag books_path, method: :get do %>
  <%= text_field_tag :search, params[:search], placeholder: 'Search...' %>
  <%= submit_tag 'Search' %>
<% end %>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @book %>
<h1><%= @book.title %></h1>

<p><strong>Description:</strong> <%= @book.description %></p>
<p><strong>Author:</strong> <%= link_to @book.author.name, author_path(@book.author) %></p>
<p><strong>Genre:</strong> <%= link_to @book.genre.name, genre_path(@book.genre) %></p>
<p><strong>Price:</strong> <%= @book.price %></p>

<div>
  <%= link_to "Edit this book", edit_book_path(@book) %> |
  <%= link_to "Back to books", books_path %>

  <%= button_to "Destroy this book", @book, method: :delete %>
</div>